/* ============================================================
   p2_data.js — part 2 of 6. The content layer.
   ============================================================
   Pure data, no behavior. Everything the app knows about interview content
   lives here, and every derived number in the UI (roadmap progress, topic
   counts, skill scores, firm drills) is computed from these arrays — so
   adding content here is all that is needed to grow the app.

   Exports (top-level consts, shared with p3-p5 by concatenation order):
     STAGES         4  staged tracks, ids s1-s4
     TOPICS        12  topics, each pinned to a stage
     QUESTIONS     78  the bank: 64 auto-graded + 14 discussion
     FIRMS         10  playbooks with per-topic weight vectors
     FERMI_MARKETS 10  settlement specs for the Fermi order-book game

   Question shape (see the full field table in README.md):
     { id, topic, diff: 1|2|3, firms: [...], title, prompt, hint, solution,
       ans?: { t: "n"|"f", v, rel?, abs?, factor?, pct?, label } }
   Omitting `ans` makes it a discussion question, graded only by self-rating.

   Referential integrity is not enforced at runtime — `topic` must match a
   TOPICS id and every entry in `firms` must match a FIRMS id, or the bank
   row will throw when it tries to render the badge. Ids are also the
   persistence keys, so never renumber an existing question.

   Difficulty calibration is deliberate and tighter than most banks: the
   classics (two ropes, the 99%-accurate test, coupon collector, 25 horses)
   are easy or medium here. diff:3 is reserved for genuinely hard material —
   100 prisoners, ABRACADABRA via optional stopping, attenuation bias,
   Gaussian orthant probabilities. Current mix: 38 easy / 29 medium / 11 hard.

   House style for solutions: derive the answer, then close with the trading
   desk translation of the idea — that last paragraph is the point of the
   bank, not the number.

   Note the QUESTIONS.push(...) block at the bottom; later additions were
   appended there rather than threaded into the literal above.
   ============================================================ */

const STAGES = [
  { id: "s1", name: "Stage 1 · Foundations", desc: "Speed and clear thinking. These are screened first and never stop mattering." },
  { id: "s2", name: "Stage 2 · Core Probability", desc: "The heart of every trading interview. Counting, conditioning, expectation." },
  { id: "s3", name: "Stage 3 · Advanced Probability & Stats", desc: "Processes, stopping times, and statistics — the JS/DE Shaw differentiators." },
  { id: "s4", name: "Stage 4 · Markets & Trading", desc: "Turn math into quotes: game theory, market making, options, estimation markets." },
];

const TOPICS = [
  { id: "mental",  stage: "s1", icon: "⚡", name: "Mental Math & Speed",            desc: "Fast, accurate arithmetic under a clock. Optiver's 80-in-8 style." },
  { id: "brain",   stage: "s1", icon: "🧩", name: "Brainteasers & Logic",            desc: "Classic puzzles that test structured reasoning, not tricks." },
  { id: "prob1",   stage: "s2", icon: "🎲", name: "Probability I · Counting & Bayes", desc: "Combinatorics, conditional probability, Bayes' rule." },
  { id: "prob2",   stage: "s2", icon: "Σ",  name: "Probability II · Expectation",     desc: "Linearity, indicators, variance, geometric tricks." },
  { id: "games",   stage: "s2", icon: "🃏", name: "Dice, Cards & Betting Games",      desc: "Fair values of games, rerolls, and simple optimal play." },
  { id: "markov",  stage: "s3", icon: "🔗", name: "Markov Chains & Random Walks",     desc: "Gambler's ruin, hitting times, pattern waiting times." },
  { id: "mart",    stage: "s3", icon: "⏱", name: "Martingales & Optimal Stopping",   desc: "Optional stopping, Wald, secretary-style decisions." },
  { id: "stats",   stage: "s3", icon: "📈", name: "Statistics & Regression",          desc: "Distributions, CLT, estimators, regression intuition." },
  { id: "gametheory", stage: "s4", icon: "♟", name: "Game Theory & Auctions",         desc: "Nash equilibria, auctions, winner's curse, adverse selection." },
  { id: "mm",      stage: "s4", icon: "⇄", name: "Market Making & Sizing",           desc: "Making markets on quantities, width, inventory, Kelly." },
  { id: "options", stage: "s4", icon: "𝜎", name: "Options & Finance",                desc: "Parity, Greeks intuition, no-arbitrage, the rule of 16." },
  { id: "fermi",   stage: "s4", icon: "🌍", name: "Fermi Estimation",                 desc: "Order-of-magnitude estimates you can defend and trade on." },
];

/* diff: 1 easy, 2 medium, 3 hard */
const QUESTIONS = [

/* ---------- Mental math ---------- */
{ id:"m1", topic:"mental", diff:1, ans:{"t":"n","v":391,"label":"17 × 23"}, firms:["optiver","imc","sig"], title:"17 × 23, in your head",
  prompt:"Compute 17 × 23 mentally. Then explain the general trick you used, and use it again on 34 × 26.",
  hint:"Both numbers are equidistant from a round number.",
  solution:"17 × 23 = (20 − 3)(20 + 3) = 400 − 9 = 391.\nDifference of squares: (a−b)(a+b) = a² − b². Any pair symmetric around a round number is instant.\n34 × 26 = (30 + 4)(30 − 4) = 900 − 16 = 884.\nInterview point: firms like Optiver want this in ~3 seconds. Drill symmetric pairs until automatic." },
{ id:"m2", topic:"mental", diff:1, ans:{"t":"n","v":2304,"label":"48²"}, firms:["optiver","imc"], title:"48² fast",
  prompt:"Compute 48² mentally, then 52², then explain why the two answers are related.",
  hint:"(50 ± 2)².",
  solution:"48² = (50 − 2)² = 2500 − 200 + 4 = 2304.\n52² = (50 + 2)² = 2500 + 200 + 4 = 2704.\nThey differ by 400 = 2 × (48 + 52) ÷ ... more usefully: consecutive-ish squares around a base differ by 4ab = 4·50·2 = 400.\nGeneral tool: (a ± b)² = a² ± 2ab + b². Base everything on 50s and 100s." },
{ id:"m3", topic:"mental", diff:1, ans:{"t":"n","v":84,"label":"3.5% of 2,400"}, firms:["optiver","sig"], title:"3.5% of 2,400",
  prompt:"What is 3.5% of 2,400? Answer in under 5 seconds, then describe your decomposition.",
  hint:"Split into 1% pieces.",
  solution:"1% of 2400 = 24. So 3% = 72 and 0.5% = 12. Total = 84.\nPercent questions decompose into 1%, 10%, 0.5% blocks. This shows up constantly in quoting: '3.5 vol points on 2,400 of vega' is the same arithmetic." },
{ id:"m4", topic:"mental", diff:1, ans:{"t":"n","v":0.4375,"label":"7/16 as a decimal"}, firms:["optiver","imc","js"], title:"7/16 as a decimal",
  prompt:"Convert 7/16 to a decimal exactly, mentally. Then give 13/16.",
  hint:"1/16 = 0.0625. Build up.",
  solution:"1/16 = 0.0625, so 7/16 = 7 × 0.0625 = 0.4375.\n13/16 = 0.8125 (= 1 − 3/16 = 1 − 0.1875).\nMemorize the sixteenths ladder: .0625 / .125 / .1875 / .25 / ... Old bond prices and many quoting drills use sixteenths and thirty-seconds." },
{ id:"m5", topic:"mental", diff:1, ans:{"t":"n","v":4838,"label":"41 × 39 + 79 × 41"}, firms:["optiver","js"], title:"41 × 39 + 79 × 41",
  prompt:"Compute 41 × 39 + 79 × 41 in your head.",
  hint:"Factor before you multiply.",
  solution:"Factor out 41: 41 × (39 + 79) = 41 × 118.\n41 × 118 = 41 × 120 − 41 × 2 = 4920 − 82 = 4838.\nLesson: scan for structure before doing any raw multiplication. Interviewers deliberately build questions where the naive path is slow." },
{ id:"m6", topic:"mental", diff:1, ans:{"t":"n","v":45.011,"rel":0.001,"label":"√2026"}, firms:["optiver","citadel"], title:"√2026 to two decimals",
  prompt:"Estimate √2026 to about two decimal places without a calculator.",
  hint:"You know a perfect square extremely close by.",
  solution:"45² = 2025, so √2026 ≈ 45 + 1/(2·45) = 45 + 0.0111 ≈ 45.01.\nLinearization: √(a² + ε) ≈ a + ε/2a. The same first-order Taylor trick prices small changes: it is exactly how you mentally adjust an option value for a small move." },

/* ---------- Brainteasers ---------- */
{ id:"b1", topic:"brain", diff:1, ans:{"t":"n","v":10,"label":"how many lockers end open"}, firms:["citadel","deshaw","jump"], title:"100 lockers",
  prompt:"100 closed lockers. Person k toggles every k-th locker (person 1 toggles all, person 2 toggles 2,4,6…, etc.) for k = 1…100. Which lockers end open?",
  hint:"A locker's final state depends on how many divisors its number has.",
  solution:"Locker n is toggled once per divisor of n. It ends open iff it is toggled an odd number of times, i.e. n has an odd number of divisors.\nDivisors pair up (d, n/d) except when d = n/d — a perfect square.\nOpen lockers: 1, 4, 9, 16, 25, 36, 49, 64, 81, 100 — the ten perfect squares." },
{ id:"b2", topic:"brain", diff:1, firms:["js","fiverings","jump"], title:"Two ropes, 45 minutes",
  prompt:"You have two ropes and a lighter. Each rope burns end-to-end in exactly 60 minutes but burns non-uniformly. Measure exactly 45 minutes.",
  hint:"Lighting both ends of a rope halves its burn time regardless of uniformity.",
  solution:"t = 0: light rope A at both ends and rope B at one end.\nt = 30: rope A finishes (both-ends burn = 30 min). Rope B has 30 minutes of burn left — now light B's other end.\nB's remaining 30 minutes halves to 15. When B finishes: t = 30 + 15 = 45.\nKey insight: 'both ends' halves remaining time no matter how irregular the rope is." },
{ id:"b3", topic:"brain", diff:2, ans:{"t":"n","v":7,"label":"minimum number of races"}, firms:["citadel","hrt","deshaw"], title:"25 horses, 5 tracks",
  prompt:"25 horses, a 5-lane track, no stopwatch — only finishing order. Minimum races to find the top 3?",
  hint:"After 5 heats and one race of winners, most horses are provably out.",
  solution:"7 races.\nRaces 1–5: five heats of 5. Race 6: the five heat winners. Label heats by their winner's finish A > B > C > D > E.\nHeat winner A is #1 overall. Candidates for #2/#3: A2, A3 (2nd/3rd in A's heat), B1, B2 (B and its runner-up), C1. Everyone else is beaten by ≥3 horses.\nRace 7: {A2, A3, B1, B2, C1} — top two finishers are overall #2 and #3.\nLower bound argument: 5 heats are forced, race 6 is needed to order winners, and after 6 races five candidates remain — one more race is necessary and sufficient." },
{ id:"b4", topic:"brain", diff:2, ans:{"t":"n","v":14,"label":"worst-case drops"}, firms:["js","citadel","hrt"], title:"Two eggs, 100 floors",
  prompt:"Two identical eggs, a 100-floor building. Find the highest safe floor with the fewest drops in the worst case. What's the optimal number and strategy?",
  hint:"Make the worst case equal no matter when the first egg breaks: decreasing gaps.",
  solution:"Answer: 14 drops.\nIf your first drop is floor k and the egg breaks, you scan 1…k−1 one by one: worst case k. To keep worst case constant, each next jump shrinks by 1: k + (k−1) + … + 1 ≥ 100 → k(k+1)/2 ≥ 100 → k = 14.\nStrategy: drop at 14, 27, 39, 50, 60, 69, 77, 84, 90, 95, 99, 100. After any break, walk up from the last safe floor.\nThis 'equalize the worst case' idea is the standard template for a whole family of search problems." },
{ id:"b5", topic:"brain", diff:2, ans:{"t":"n","v":98,"label":"coins the senior pirate keeps"}, firms:["fiverings","sig","deshaw"], title:"Five pirates, 100 coins",
  prompt:"Five perfectly rational pirates (strict seniority) split 100 gold coins. The most senior proposes a split; all vote (proposer included); majority or tie passes, otherwise the proposer is thrown overboard and the next proposes. Pirates value: staying alive, then gold, then seeing others die. What does the senior pirate propose?",
  hint:"Solve it backwards from 2 pirates.",
  solution:"Backward induction.\n2 pirates: senior proposes (100, 0) — his own vote ties, passes.\n3 pirates: pirate 3 offers pirate 1 a single coin (better than the 0 he'd get with two pirates left): (99, 0, 1).\n4 pirates: needs one more vote; buys pirate 2 (who gets 0 in the 3-pirate world): (99, 0, 1, 0) reading senior→junior.\n5 pirates: needs two votes besides his own; buys the two who get nothing in the 4-pirate world (pirates 3 and 1): (98, 0, 1, 0, 1).\nThe senior pirate keeps 98. The interview skill: backward induction and 'pay only the cheapest pivotal voters'." },
{ id:"b6", topic:"brain", diff:1, ans:{"t":"n","v":7.5,"label":"angle in degrees"}, firms:["optiver","imc","sig"], title:"Clock hands at 3:15",
  prompt:"What is the angle between the hour and minute hands at 3:15?",
  hint:"The hour hand moves too.",
  solution:"Minute hand at 15 min = 90°.\nHour hand: 3 hours + 15 min = 3.25 hours × 30°/hour = 97.5°.\nAngle = 97.5° − 90° = 7.5°.\nThe trap is forgetting the hour hand drifts 0.5° per minute. Follow-up they love: 'when after 3:00 do the hands coincide?' → 180/11 min ≈ 3:16:22." },

/* ---------- Probability I ---------- */
{ id:"p1", topic:"prob1", diff:1, ans:{"t":"n","v":0.18182,"rel":0.03,"pct":1,"label":"P(sum = 8 | at least one 6) — fraction or decimal"}, firms:["js","sig","citadel"], title:"Sum is 8, given a six",
  prompt:"Two fair dice are rolled. Given that at least one die shows a 6, what is the probability the sum is 8?",
  hint:"Count the conditioning set carefully — (6,6) is one outcome, not two.",
  solution:"Outcomes with at least one 6: 36 − 25 = 11.\nOf these, sum = 8: (2,6) and (6,2) → 2 outcomes.\nAnswer: 2/11.\nClassic trap: intuition says 'the other die must be a 2, so 1/6.' Wrong because 'at least one 6' is not the same as 'die #1 shows 6' — the conditioning set has 11 elements, not 12." },
{ id:"p2", topic:"prob1", diff:1, ans:{"t":"n","v":0.66667,"rel":0.02,"pct":1,"label":"P(other side red)"}, firms:["js","sig","fiverings"], title:"Three cards, one red face up",
  prompt:"Three cards: one red on both sides, one blue on both sides, one red/blue. Pick a card and side at random; you see red. What's the probability the other side is red?",
  hint:"Count red faces, not cards.",
  solution:"There are 3 red faces: two on the red-red card, one on the mixed card. Given you see a red face, each is equally likely.\n2 of the 3 red faces have red on the back.\nAnswer: 2/3.\nThe error path is 'it's either the RR or RB card, so 1/2' — that ignores that the RR card is twice as likely to show you red." },
{ id:"p3", topic:"prob1", diff:1, ans:{"t":"n","v":0.0045249,"rel":0.03,"pct":1,"label":"P(both aces)"}, firms:["citadel","deshaw"], title:"Two aces off the top",
  prompt:"You draw two cards from a shuffled 52-card deck. What is the probability both are aces? And the probability of at least one ace?",
  hint:"Sequential multiplication for the first; complement for the second.",
  solution:"Both aces: (4/52) × (3/51) = 12/2652 = 1/221 ≈ 0.45%.\nAt least one ace: 1 − P(no aces) = 1 − (48/52)(47/51) = 1 − 2256/2652 = 396/2652 ≈ 14.9%.\nHabit to build: 'at least one' should trigger the complement automatically." },
{ id:"p4", topic:"prob1", diff:1, ans:{"t":"n","v":0.25,"pct":1,"label":"P(no collision)"}, firms:["js","jump","hrt"], title:"Ants on a triangle",
  prompt:"Three ants sit on the corners of a triangle. Each simultaneously picks a random edge direction and walks along it. Probability of no collision?",
  hint:"Collisions are avoided only if they all rotate the same way.",
  solution:"Each ant picks one of 2 directions → 8 equally likely configurations.\nNo collision iff all go clockwise or all go counterclockwise: 2 configurations.\nAnswer: 2/8 = 1/4.\nFollow-up: n ants on an n-gon → 2/2ⁿ = 2^{1−n}." },
{ id:"p5", topic:"prob1", diff:1, ans:{"t":"n","v":0.5,"pct":1,"label":"P(disease | positive)"}, firms:["citadel","deshaw","sig"], title:"The 99% accurate test",
  prompt:"A disease affects 1% of a population. A test is 99% sensitive (detects the disease when present) and has a 1% false-positive rate. You test positive. Probability you have the disease?",
  hint:"Run 10,000 imaginary people through the test.",
  solution:"Per 10,000 people: 100 have the disease → 99 true positives. 9,900 don't → 99 false positives.\nP(disease | positive) = 99 / (99 + 99) = 1/2.\nA '99% accurate' test with 1% prevalence is a coin flip. Base rates dominate — the same logic tells you why a backtest with weak priors and a huge search space produces mostly false discoveries." },
{ id:"p6", topic:"prob1", diff:3, ans:{"t":"n","v":0.48148,"rel":0.02,"pct":1,"label":"P(both boys)"}, firms:["js","fiverings"], title:"Both children, one boy born on Tuesday",
  prompt:"A family has two children. You learn that at least one is a boy born on a Tuesday. What is the probability both are boys? (Assume boys/girls and weekdays are uniform and independent.)",
  hint:"Enumerate (sex, weekday) pairs for both children; the Tuesday detail changes the count.",
  solution:"Each child has 14 equally likely types (sex × weekday). Condition on 'at least one is (Boy, Tue)'.\nTotal such families: 14 + 14 − 1 = 27 (first child B-Tue: 14 choices for other; second child B-Tue: 14; subtract the double-counted both-B-Tue).\nBoth boys among them: first is B-Tue (7 choices of brother's day) + second is B-Tue (7) − both B-Tue (1) = 13.\nAnswer: 13/27 ≈ 0.481 — not 1/3.\nThe more specific the information about 'which' child, the closer the answer moves to 1/2. Great test of disciplined enumeration." },

/* ---------- Probability II ---------- */
{ id:"e1", topic:"prob2", diff:1, ans:{"t":"n","v":6,"label":"expected rolls"}, firms:["js","sig","optiver"], title:"Rolls until a six",
  prompt:"On average, how many rolls of a fair die until you see the first 6? Prove it two ways.",
  hint:"Geometric distribution — or set up a one-step recursion.",
  solution:"Answer: 6.\nWay 1: number of rolls is Geometric(1/6); mean = 1/p = 6.\nWay 2 (recursion): E = 1 + (5/6)E → E/6 = 1 → E = 6.\nThe recursion method generalizes to almost every 'expected time until X' question, so make sure you can produce it on demand." },
{ id:"e2", topic:"prob2", diff:1, ans:{"t":"n","v":4.25,"label":"expected value with optimal play"}, firms:["js","sig","fiverings"], title:"Die with one reroll",
  prompt:"Roll a fair die. You may keep the result or reroll once (you must keep the second roll). Playing optimally, what is the game's expected value?",
  hint:"Compare each first roll to the value of rerolling.",
  solution:"A reroll is worth E[die] = 3.5. So keep any first roll > 3.5, i.e. keep 4, 5, 6; reroll 1, 2, 3.\nEV = P(keep)·E[roll | keep] + P(reroll)·3.5 = (1/2)(5) + (1/2)(3.5) = 4.25.\nThis threshold structure — 'continue iff current value < value of continuing' — is the seed of every optimal-stopping question." },
{ id:"e3", topic:"prob2", diff:2, ans:{"t":"n","v":3.99,"abs":0.05,"label":"expected distinct faces"}, firms:["js","citadel","deshaw"], title:"Distinct faces in six rolls",
  prompt:"Roll a fair die 6 times. What is the expected number of distinct faces that appear?",
  hint:"Indicator per face + linearity.",
  solution:"Let Iₖ indicate face k appears. P(face k missing in 6 rolls) = (5/6)⁶ ≈ 0.335.\nE[distinct] = 6 × (1 − (5/6)⁶) ≈ 6 × 0.665 = 3.99.\nLinearity of expectation needs no independence — this is the single most-used trick in quant interviews. If your first instinct on any 'expected number of…' question isn't indicators, retrain it." },
{ id:"e4", topic:"prob2", diff:1, ans:{"t":"n","v":14.7,"abs":0.15,"label":"expected rolls to see all six"}, firms:["js","deshaw","hrt"], title:"Coupon collector, die edition",
  prompt:"Roll a die repeatedly. Expected number of rolls until you've seen all six faces?",
  hint:"Time to each 'new' face is geometric with a shrinking success probability.",
  solution:"After seeing k faces, P(new face) = (6−k)/6, so the wait is 6/(6−k).\nE = 6/6 + 6/5 + 6/4 + 6/3 + 6/2 + 6/1 = 6(1 + 1/2 + 1/3 + 1/4 + 1/5 + 1/6) = 14.7.\nGeneral form: n·Hₙ. Also worth knowing: the last coupon takes n rolls on average — as long as everything before it combined-ish." },
{ id:"e5", topic:"prob2", diff:2, ans:{"t":"n","v":0.5,"pct":1,"label":"P(passenger 100 gets own seat)"}, firms:["js","citadel","fiverings"], title:"The 100th passenger",
  prompt:"100 passengers board in order; passenger 1 lost his ticket and sits uniformly at random. Everyone else sits in their own seat if free, otherwise picks a random free seat. Probability passenger 100 gets his own seat?",
  hint:"Track only two special seats: #1 and #100.",
  solution:"Answer: 1/2.\nAt every random choice, the chooser is equally likely to pick seat 1 or seat 100 (both are symmetric: choosing either ends the cascade — seat 1 resolves everything in passenger 100's favor, seat 100 against). All other choices just pass the problem along.\nSo the process ends with seat 1 or seat 100 taken first, with equal probability → 1/2.\nSaying '1/2 by symmetry' is fine, but you must articulate WHICH symmetry, or the interviewer will push." },
{ id:"e6", topic:"prob2", diff:1, ans:{"t":"n","v":2.9167,"abs":0.06,"label":"Var of one die roll"}, firms:["citadel","deshaw","optiver"], title:"Variance of a die",
  prompt:"Compute the variance of one fair die roll. Then, without further computation, give the variance and standard deviation of the sum of 10 dice.",
  hint:"E[X²] first. Variances add for independent rolls.",
  solution:"E[X] = 3.5. E[X²] = (1+4+9+16+25+36)/6 = 91/6.\nVar = 91/6 − 12.25 = 35/12 ≈ 2.92.\nSum of 10 independent dice: Var = 350/12 ≈ 29.17, σ ≈ 5.4.\nWhy traders care: 'fair 35, σ ≈ 5.4' is exactly how you should size a market on the sum of 10 dice — width scales with σ, and σ scales with √n." },

/* ---------- Dice / cards / betting games ---------- */
{ id:"g1", topic:"games", diff:1, ans:{"t":"n","v":12.25,"label":"fair value ($)"}, firms:["js","optiver","sig"], title:"Price the product of two dice",
  prompt:"A game pays the product of two fair dice, in dollars. What's the fair price? What would you actually quote as a market maker?",
  hint:"Independence lets you multiply expectations.",
  solution:"Fair value: E[XY] = E[X]E[Y] = 3.5² = 12.25 (independence).\nAs a quote: you need width for variance. σ of the product ≈ 8.9 (E[X²Y²] = (91/6)² ≈ 230, Var ≈ 230 − 150 = 80). A market like 11.5 – 13 for small size is defensible; tighten with more flow, widen with size.\nInterviewers want: fair value fast, then unprompted awareness that a quote is fair value ± compensation for risk." },
{ id:"g2", topic:"games", diff:2, ans:{"t":"n","v":4.66667,"abs":0.05,"label":"EV with optimal play"}, firms:["js","fiverings","sig"], title:"Three rolls, keep the last",
  prompt:"Roll a die up to 3 times; after each roll you may stop and take that value, but if you roll again you lose the previous roll. Optimal strategy and EV?",
  hint:"Work backwards from the last roll.",
  solution:"Backward induction.\nRoll 3 alone is worth 3.5.\nRoll 2: keep if ≥ 4 (beats 3.5). Value = (1/2)(5) + (1/2)(3.5) = 4.25.\nRoll 1: keep if ≥ 5 (beats 4.25). Value = (2/6)(5.5) + (4/6)(4.25) = 11/6 + 17/6 = 14/3 ≈ 4.67.\nStrategy: keep 5–6 on roll 1; keep 4–6 on roll 2; take roll 3.\nNote the threshold rises the more chances remain — more optionality makes you pickier." },
{ id:"g3", topic:"games", diff:1, ans:{"t":"n","v":0.54545,"rel":0.02,"pct":1,"label":"P(7 before 8)"}, firms:["sig","optiver","imc"], title:"Seven before eight",
  prompt:"Roll two dice repeatedly. What's the probability a sum of 7 appears before a sum of 8?",
  hint:"Ignore every roll that is neither.",
  solution:"P(7) = 6/36, P(8) = 5/36. Conditional on the game ending this roll, P(7 first) = 6/(6+5) = 6/11 ≈ 0.545.\nAll other rolls are irrelevant — the geometric 'race' reduces to relative probabilities. This 'condition on a decisive trial' move kills a whole class of questions instantly." },
{ id:"g4", topic:"games", diff:2, firms:["js","sig"], title:"St. Petersburg, briefly",
  prompt:"A game: flip a fair coin until the first head, and get paid 2ⁿ dollars where n is the number of flips. The EV is infinite. How much would you actually pay to play once, and why?",
  hint:"Separate the EV computation from the decision — what matters for one play?",
  solution:"EV = Σ (1/2ⁿ)(2ⁿ) = 1 + 1 + 1 + … = ∞, but nobody pays more than ~$10-20. Good answers mention several of:\n• Bankroll/utility: log utility caps the certainty equivalent (for wealth W it's roughly log₂W + 2 dollars).\n• The counterparty can't pay 2⁵⁰ — truncating at a credible cap of 2ᵏ makes EV ≈ k + 1 dollars.\n• One-shot variance: median payoff is 2; you get ≤ 4 with prob 3/4.\nThe question tests whether you understand that price = f(EV, variance, credit, repetition), not EV alone. Traders live in the gap between expectation and what you can actually monetize." },
{ id:"g5", topic:"games", diff:2, ans:{"t":"n","v":0.5,"pct":1,"label":"win probability of the best strategy"}, firms:["fiverings","js","sig"], title:"Bet on the next card",
  prompt:"A shuffled deck is dealt face up one card at a time. Once, at any moment of your choosing (before any deal, based on everything seen), you must bet that the NEXT card is red. When should you bet to maximize the win probability?",
  hint:"Compute the value of betting now vs. waiting — or find the martingale.",
  solution:"It doesn't matter: every strategy wins with probability exactly 1/2.\nSlick proof: your strategy picks a stopping time; couple the game with 'bet that the LAST card is red' — the next card after your stop and the bottom card of the deck are exchangeable, and P(bottom card red) = 1/2 regardless of anything you observed.\nEquivalently, the proportion of reds remaining is a martingale — no stopping rule beats it.\nThis is the cleanest interview gateway to optional stopping: you cannot out-time a fair game." },

/* ---------- Markov ---------- */
{ id:"k1", topic:"markov", diff:1, ans:{"t":"n","v":0.3,"abs":0.01,"pct":1,"label":"P(reach $100), fair coin"}, firms:["js","citadel","deshaw"], title:"Gambler's ruin, fair coin",
  prompt:"You have $30 and bet $1 on fair coin flips until you hit $0 or $100. Probability you reach $100? What if the coin pays you with probability 0.49?",
  hint:"Fair case: find the martingale. Biased case: know the geometric formula.",
  solution:"Fair: wealth is a martingale, so E[final] = 30 = 100·p → p = 30%.\nBiased (p = 0.49): P(reach N from k) = (1 − (q/p)ᵏ)/(1 − (q/p)ᴺ) with q/p = 51/49 ≈ 1.0408.\n(q/p)³⁰ ≈ 3.32, (q/p)¹⁰⁰ ≈ 54.6 → P ≈ (1 − 3.32)/(1 − 54.6) ≈ 4.3%.\nThe brutal takeaway: a 1% edge against you turns 30% into ~4%. Small negative edges compound viciously — the entire logic of transaction costs in one formula." },
{ id:"k2", topic:"markov", diff:2, ans:{"t":"n","v":9,"label":"expected steps"}, firms:["js","hrt","jump"], title:"Time to leave [−3, 3]",
  prompt:"A symmetric ±1 random walk starts at 0. What is the expected number of steps until it hits +3 or −3?",
  hint:"Sₙ² − n is a martingale.",
  solution:"Answer: 9.\nSₙ² − n is a martingale; optional stopping at the exit time T: E[S_T²] = E[T]. Since |S_T| = 3 always, E[T] = 9.\nGeneral: exit time of (−a, b) has E[T] = ab. Worth memorizing — it anchors intuition that diffusion covers distance in time ∝ distance²." },
{ id:"k3", topic:"markov", diff:1, ans:{"t":"n","v":42,"label":"expected rolls for 66"}, firms:["js","sig","citadel"], title:"Waiting for HH, then for 66",
  prompt:"Expected number of fair coin flips to see HH (two heads in a row)? Then: expected die rolls to see two 6s in a row?",
  hint:"Set up states: 'no progress' and 'one head so far'.",
  solution:"States: E₀ (no progress), E₁ (just saw one H).\nE₀ = 1 + ½E₁ + ½E₀,  E₁ = 1 + ½·0 + ½E₀ → E₀ = 6.\nDice: E₀ = 1 + (1/6)E₁ + (5/6)E₀; E₁ = 1 + (5/6)E₀ → E₀ = 42.\nPattern for 'k-in-a-row of an outcome with prob 1/n': n + n² + … + nᵏ. So HH = 2 + 4 = 6, and 66 = 6 + 36 = 42.\nContrast question they love: waiting for HT is only 4 — order matters because of self-overlap." },
{ id:"k4", topic:"markov", diff:2, ans:{"t":"n","v":10,"label":"expected steps to opposite vertex"}, firms:["js","fiverings","hrt"], title:"Cube walk",
  prompt:"A particle random-walks on the vertices of a cube, moving to one of the 3 adjacent vertices each step uniformly. Expected number of steps to reach the opposite vertex?",
  hint:"Group vertices by distance from the start: 0, 1, 2, 3 edges away.",
  solution:"By symmetry, only the distance to the target vertex matters: d ∈ {0, 1, 2, 3} edges. Let E_d = expected steps to reach the target from distance d.\nFrom d = 1: one of 3 neighbors is the target, the other two are at d = 2 → E₁ = 1 + (2/3)E₂.\nFrom d = 2: two neighbors are at d = 1, one is at d = 3 → E₂ = 1 + (2/3)E₁ + (1/3)E₃.\nFrom d = 3 (the start): all three neighbors are at d = 2 → E₃ = 1 + E₂.\nSubstitute: E₂ = 1 + (2/3)E₁ + (1/3)(1 + E₂) → E₂ = 2 + E₁. Then E₁ = 1 + (2/3)(2 + E₁) → E₁ = 7, E₂ = 9, E₃ = 10.\nAnswer: 10 steps.\nSanity check: for random walks on regular graphs, expected return time to a vertex = number of vertices = 8; the antipode taking a bit longer than that feels right." },
{ id:"k5", topic:"markov", diff:1, ans:{"t":"n","v":0.4,"abs":0.01,"pct":1,"label":"long-run fraction of rainy days"}, firms:["citadel","jump","tower"], title:"Rain chain",
  prompt:"Weather is Markov: if it rains today, it rains tomorrow with prob 0.7; if dry, it rains tomorrow with prob 0.2. Long-run fraction of rainy days? And if it's raining Monday, what's P(rain Wednesday)?",
  hint:"Stationary distribution: flow in = flow out.",
  solution:"Stationary π: π·0.3 = (1−π)·0.2 → π = 0.4. It rains 40% of days in the long run.\nTwo-step from rain: P = 0.7·0.7 + 0.3·0.2 = 0.55.\nNote 0.55 is already drifting from 0.7 toward the stationary 0.4 — mixing at rate |0.7 − 0.2| = 0.5 per step (the second eigenvalue). Interviewers often probe whether you know the chain forgets its start geometrically fast." },

/* ---------- Martingales / stopping ---------- */
{ id:"mg1", topic:"mart", diff:2, ans:{"t":"n","v":7,"label":"expected payout ($)"}, firms:["js","deshaw"], title:"Wald's identity in one flip",
  prompt:"Flip a fair coin until the first head; call the number of flips N. You then roll N dice and get paid their sum. Expected payout? Justify carefully.",
  hint:"E[N] = 2. Why are you allowed to multiply?",
  solution:"E[payout] = E[N] × E[die] = 2 × 3.5 = 7.\nJustification is Wald's identity: for iid Xᵢ and a stopping time N (here N is even decided before any dice are rolled), E[X₁ + … + X_N] = E[N]·E[X].\nThe interviewer's follow-up: when does this FAIL? When N is NOT a stopping time — when it peeks at the future. Example: 'sum the rolls, but stop right before the first 6' has E[X | kept] ≠ 3.5, so the product formula breaks. Wald DOES still hold for rules like 'stop once the running sum exceeds 10', because that decision uses only the past. Knowing the boundary of the theorem — stopping time vs. clairvoyant time — is the point of the question." },
{ id:"mg2", topic:"mart", diff:2, ans:{"t":"n","v":10,"label":"expected flips"}, firms:["js","fiverings","deshaw"], title:"Expected flips until HTH",
  prompt:"What is the expected number of fair coin flips until the pattern HTH first appears? Solve it with the casino/martingale trick if you can.",
  hint:"Imagine a gambler starting at every flip, each betting the pattern letter-by-letter at fair odds.",
  solution:"Answer: 10.\nABRACADABRA argument: before each flip a new gambler arrives with $1 and bets it on 'this flip starts HTH', parlaying at fair odds. The total money in play is a martingale. When HTH completes at time T, surviving gamblers hold: the one who started at T−2 has $8 (won H, T, H), and the one who started at T (betting just 'H') holds $2. All others lost $1 each.\nOptional stopping: E[T] = total stakes = 8 + 2 = 10.\nRule: E[T] = Σ 2ᵏ over every prefix of the pattern that is also a suffix (here HTH itself and H).\nCross-check: HH gives 4 + 2 = 6 ✓, HT gives 4 ✓." },
{ id:"mg3", topic:"mart", diff:1, ans:{"t":"n","v":0.37,"abs":0.025,"pct":1,"label":"success probability"}, firms:["js","sig","fiverings"], title:"The secretary rule",
  prompt:"You'll see 100 candidates in random order, must accept or reject each immediately, and want the single best. What's the optimal strategy, and roughly the probability it succeeds?",
  hint:"Observe for a while, then take the first record-breaker.",
  solution:"Optimal: reject the first ~100/e ≈ 37 candidates, then accept the first one better than everything seen so far.\nSuccess probability → 1/e ≈ 37% (for the strategy with cutoff n/e).\nWhy it works: you succeed if the best is after the cutoff AND the best-before-it lands in the observation window; summing gives (r/n)·ln(n/r), maximized at r = n/e.\nTrading relevance: it's the cleanest model of 'when do I stop looking and act' — and the 37% number itself gets asked cold." },
{ id:"mg4", topic:"mart", diff:2, firms:["js","deshaw","citadel"], title:"Stop when you're ahead?",
  prompt:"You flip a fair coin, +$1 heads, −$1 tails, and plan to 'quit as soon as I'm up $1.' You'll succeed with probability 1. So is this a money machine? What's E[time], and what breaks in practice?",
  hint:"The walk hits +1 almost surely — but check the expected time and the required bankroll.",
  solution:"P(hit +1 eventually) = 1 for a symmetric walk, but E[time to hit +1] = ∞, and the strategy needs unbounded credit: before finishing you may be arbitrarily deep underwater (the minimum has heavy tails).\nOptional stopping doesn't apply because T is not 'nice' (unbounded, E[T] = ∞) — that's exactly why E[S_T] = 1 ≠ 0 = S₀ doesn't contradict the martingale property.\nWith any finite bankroll b, P(success) = b/(b+1) and the loss when ruined is −b: EV is exactly 0 again.\nThis is the mathematically honest version of 'martingale betting systems don't work,' and interviewers use it to test whether you really understand optional stopping's conditions." },
{ id:"mg5", topic:"mart", diff:2, firms:["sig","js"], title:"Pick the best envelope of two",
  prompt:"Two sealed envelopes contain different unknown numbers. You open one, see its value, and may keep it or switch. Can you beat 50% probability of ending with the larger number?",
  hint:"Introduce your own randomness: a threshold drawn from a distribution with full support.",
  solution:"Yes — Cover's trick. Draw your own threshold T from any distribution positive everywhere (e.g. exponential). Keep the opened value if it exceeds T, otherwise switch.\nIf both numbers are on the same side of T, you're at 50%. But with positive probability T lands strictly between them — and then you win for sure.\nOverall: strictly better than 1/2 against ANY pair of numbers.\nMoral traders love: injecting calibrated randomness can extract edge where none seems to exist; certainty about 'no information' is often wrong." },

/* ---------- Stats ---------- */
{ id:"s1", topic:"stats", diff:1, ans:{"t":"n","v":0.5,"pct":1,"label":"P(X > 2Y)"}, firms:["citadel","deshaw","js"], title:"P(X > 2Y) for standard normals",
  prompt:"X and Y are independent standard normals. What is P(X > 2Y)? What about P(X > 2Y + 1)?",
  hint:"X − 2Y is itself normal.",
  solution:"X − 2Y ~ N(0, 1 + 4) = N(0, 5). By symmetry about 0: P(X − 2Y > 0) = 1/2.\nSecond part: P(N(0,5) > 1) = P(Z > 1/√5) = P(Z > 0.447) ≈ 0.327.\nAny linear combination of independent normals is normal — recognizing 'this reduces to one normal' is the entire question." },
{ id:"s2", topic:"stats", diff:1, ans:{"t":"n","v":0,"abs":0.001,"label":"Corr(X, X²)"}, firms:["deshaw","citadel","hrt"], title:"Uncorrelated but dependent",
  prompt:"X ~ N(0,1). What is the correlation between X and X²? Are they independent? Give the general lesson.",
  hint:"You need E[X·X²] = E[X³].",
  solution:"Cov(X, X²) = E[X³] − E[X]E[X²] = 0 − 0 = 0 (odd moments of a symmetric distribution vanish). Correlation = 0.\nBut they're maximally dependent — X² is a function of X.\nLesson: correlation only detects LINEAR relationships. In markets: returns are roughly uncorrelated day to day, but |returns| are strongly autocorrelated (vol clustering) — same structure as this toy example, and a favorite follow-up." },
{ id:"s3", topic:"stats", diff:2, ans:{"t":"n","v":1.0,"abs":0.02,"label":"slope of B on A"}, firms:["citadel","deshaw","tower"], title:"Regression beta from correlation",
  prompt:"Stock A's daily returns have volatility 2%, stock B's 4%, correlation 0.5. You regress B on A: what's the slope? What fraction of B's variance is explained? And the slope of A on B?",
  hint:"β = ρ·σ_B/σ_A. R² = ρ².",
  solution:"β(B on A) = ρ σ_B/σ_A = 0.5 × (4/2) = 1.0.\nR² = ρ² = 0.25 — only a quarter of B's variance is explained despite β = 1.\nA on B: β = 0.5 × (2/4) = 0.25 — NOT 1/1.0. The product of the two slopes is ρ² ≤ 1; regression is not invertible.\nHedging translation: to hedge 1 share of B you short 1 'unit' of A's return... but the hedge still leaves 75% of the variance. β tells you the hedge ratio; ρ² tells you if the hedge is any good." },
{ id:"s4", topic:"stats", diff:2, firms:["deshaw","citadel","js"], title:"MLE for Uniform[0, θ]",
  prompt:"You observe n iid draws from Uniform[0, θ]. What's the MLE of θ? Is it biased? How would you correct it?",
  hint:"The likelihood is (1/θ)ⁿ on θ ≥ max(xᵢ) — where is it maximized?",
  solution:"Likelihood = θ⁻ⁿ · 1{θ ≥ max xᵢ}, decreasing in θ, so MLE = max(xᵢ).\nBiased low: E[max] = θ·n/(n+1) (the max of n uniforms sits at n/(n+1) of the range on average).\nUnbiased corrections: (n+1)/n · max, or the German-tank flavor max + max/n − ... (the classic 'German tank problem' estimator max·(1 + 1/n) − 1 in the discrete case).\nWhy quants ask it: it's the simplest case where the MLE sits ON the boundary of the data — good probe of whether you actually understand likelihoods vs. just memorized calculus." },
{ id:"s5", topic:"stats", diff:1, ans:{"t":"n","v":0.0017,"abs":0.0009,"pct":1,"label":"P(sum > 400)"}, firms:["citadel","optiver","imc"], title:"100 dice above 400",
  prompt:"Roll 100 dice. Estimate the probability the sum exceeds 400.",
  hint:"CLT. You'll want σ of one die ≈ 1.71.",
  solution:"Mean = 350. Var = 100 × 35/12 ≈ 291.7, σ ≈ 17.1.\nz = (400.5 − 350)/17.1 ≈ 2.96 (continuity correction; ≈2.93 without).\nP ≈ 0.15%–0.2%.\nBar to clear: know Φ tail landmarks cold — 1σ:16%, 2σ:2.3%, 3σ:0.13% — traders quote event probabilities off these constantly." },
{ id:"s6", topic:"stats", diff:1, ans:{"t":"n","v":0.66667,"rel":0.02,"label":"E[max(U, V)]"}, firms:["js","sig","hrt"], title:"Max and min of two uniforms",
  prompt:"U, V are independent Uniform[0,1]. Find E[max(U,V)] and E[min(U,V)], and the correlation sign between max and min.",
  hint:"P(max ≤ x) = x². Or use symmetry: max + min = U + V.",
  solution:"P(max ≤ x) = x² → density 2x → E[max] = 2/3.\nmax + min = U + V → E[min] = 1 − 2/3 = 1/3.\nCorrelation is positive: Cov(max,min) = E[UV] − (2/3)(1/3) = 1/4 − 2/9 = 1/36 > 0.\nOrder statistics of uniforms (k-th of n has mean k/(n+1)) power a surprising number of interview questions — memorize the k/(n+1) rule." },

/* ---------- Game theory ---------- */
{ id:"gt1", topic:"gametheory", diff:1, ans:{"t":"n","v":0,"abs":0.5,"label":"Nash equilibrium pick"}, firms:["fiverings","sig","js"], title:"Two-thirds of the average",
  prompt:"Everyone in a group picks a number in [0,100]; closest to ⅔ of the group average wins. What do you pick against perfectly rational players? Against a real room of interviewees?",
  hint:"Iterate the dominance argument — then ask how many steps real people iterate.",
  solution:"Rational: no one plays above 66.7 (⅔·100). If all ≤ 66.7, target ≤ 44.4; iterating drives everything to 0 — unique Nash equilibrium: everyone picks 0.\nReal rooms: level-1 players pick 33 (⅔ of 50), level-2 pick 22; empirical winners cluster around 15–25.\nThe interview answer: 'Nash is 0; against humans I'd pick ~20, because you profit from being exactly one step ahead of the field, not infinitely ahead.' That last sentence is the trading lesson." },
{ id:"gt2", topic:"gametheory", diff:2, ans:{"t":"n","v":0.5,"rel":0.02,"label":"bid as a fraction of your value"}, firms:["fiverings","citadel","deshaw"], title:"First-price auction, two bidders",
  prompt:"Two bidders with private values drawn iid Uniform[0,1] compete in a sealed-bid first-price auction. Find the symmetric equilibrium bidding strategy.",
  hint:"Guess b(v) = c·v and verify, or set up the win-probability tradeoff.",
  solution:"Equilibrium: bid half your value, b(v) = v/2.\nDerivation: if opponent bids βw with w ~ U[0,1], bidding b wins with prob P(βw < b) = b/β and profits (v − b): maximize (v−b)·b/β → b = v/2. Consistency forces β = 1/2 ✓.\nShading intuition: you trade off win probability against margin; with n bidders the equilibrium is b = v(n−1)/n — competition compresses margins toward value.\nMarket-making version: quoting aggressively wins more flow at worse prices — the auction shading tradeoff IS the spread-setting tradeoff." },
{ id:"gt3", topic:"gametheory", diff:1, firms:["sig","fiverings","js"], title:"The jar of coins auction",
  prompt:"An interviewer auctions a jar of coins. Everyone privately estimates its value and bids. Why does the winner usually lose money, and how should you bid?",
  hint:"Condition on the event 'my bid won'.",
  solution:"Winner's curse: estimates are value + noise, and the auction systematically selects the MOST optimistic estimate. Winning is bad news — conditional on winning, your estimate was likely the highest error.\nCorrect play: bid as if your estimate is the maximum of n draws, i.e. shade down E[value | my estimate is the highest], and shade MORE with more bidders (opposite of naive instinct).\nTrading version: getting filled instantly on your bid often means you're the most wrong person in the market at that moment — adverse selection is the winner's curse in continuous time. SIG explicitly teaches this in poker terms: 'if everyone folds to your raise, your raise was too small... if you always get called, too big.'" },
{ id:"gt4", topic:"gametheory", diff:2, ans:{"t":"n","v":0.5,"rel":0.02,"pct":1,"label":"equilibrium weight on PAPER"}, firms:["fiverings","sig","hrt"], title:"RPS where rock pays double",
  prompt:"Zero-sum rock-paper-scissors, except winning WITH ROCK pays $2 instead of $1 (other wins pay $1, ties nothing). Find the equilibrium mix.",
  hint:"Make your opponent indifferent between all three throws.",
  solution:"Let opponent play (r, p, s). Your payoffs: U(R) = 2s − p, U(P) = r − s, U(S) = p − 2r.\nIndifference: 2s − p = r − s = p − 2r with r + p + s = 1.\nFrom the first pair: 3s = r + p = 1 − s → s = 1/4. From the second: 3r = p + s = 1 − r → r = 1/4. So p = 1/2.\nEquilibrium: (rock, paper, scissors) = (¼, ½, ¼); game value 0.\nCounterintuition worth saying aloud: the rock bonus makes you play PAPER more (to tax opponent's rock) and rock no more than baseline — the equilibrium response to a juiced strategy is to defend against it, not to spam it." },
{ id:"gt5", topic:"gametheory", diff:1, ans:{"t":"n","v":1,"label":"flags to take on move 1"}, firms:["fiverings","jump","js"], title:"21 flags",
  prompt:"21 flags; players alternate taking 1–3 flags; whoever takes the last flag wins. Do you move first or second, and what's the strategy?",
  hint:"Which totals are losing positions?",
  solution:"Positions ≡ 0 (mod 4) are losing for the player to move. 21 mod 4 = 1, so move FIRST and take 1, leaving 20.\nThen mirror: whatever k your opponent takes, take 4 − k, marching 20 → 16 → 12 → 8 → 4 → 0.\nGeneral: with take 1..m, losing positions are multiples of m+1. Say the invariant, not just the move — interviewers grade the generalization." },

/* ---------- Market making ---------- */
{ id:"mm1", topic:"mm", diff:1, firms:["js","optiver","sig"], title:"Make me a market on NYC windows",
  prompt:"'Make me a market on the number of windows in Manhattan, in millions.' Walk through the full protocol: estimate, quote, and how you respond when the interviewer trades against you.",
  hint:"Fair value first, then width from your uncertainty, then update from their trade.",
  solution:"1) Fair value: ~1.6M residents in Manhattan, ~1M housing units, ~5 windows each ≈ 5M residential; offices/retail plausibly similar or more → order 10–20M. Say fair ≈ 15M.\n2) Quote around fair with width reflecting your σ: e.g. 10M bid / 20M ask. Never quote tighter than your honest uncertainty just to look confident.\n3) They lift your offer (buy at 20M): update — they may know it's higher. Re-quote higher and/or wider (e.g. 15/25), and smaller if unsure. If they keep lifting, keep moving: repeated one-way flow means you're wrong, not that they're generous.\n4) Endgame: be able to say what would change your fair (a fact about office window density, say).\nGraded on: sane decomposition, width ∝ uncertainty, correct direction of updates, no panic." },
{ id:"mm2", topic:"mm", diff:1, ans:{"t":"n","v":0.2,"rel":0.02,"pct":1,"label":"Kelly fraction"}, firms:["js","sig","citadel"], title:"Kelly, the two-line version",
  prompt:"A bet wins with p = 0.6 at even money. What fraction of bankroll does Kelly say to bet, what growth does it buy, and why do pros bet less than Kelly?",
  hint:"f* = p − q for even money.",
  solution:"Even-money Kelly: f* = p − q = 0.6 − 0.4 = 20% of bankroll.\nGrowth: g = p·ln(1+f) + q·ln(1−f); at f* ≈ 0.0201 per bet (~2% geometric growth).\nWhy bet half-Kelly: (a) p is estimated, and overbetting is punished more than underbetting (growth is concave with a cliff — betting 2× Kelly gives ZERO growth, beyond that negative); (b) drawdown tolerance: full Kelly has 50% chance of halving before doubling... roughly, painful swings; (c) parameter drift.\nThe asymmetry sentence — 'the penalty for oversizing exceeds the penalty for undersizing' — is the answer interviewers wait for." },
{ id:"mm3", topic:"mm", diff:2, ans:{"t":"n","v":35,"label":"fair value of the sum"}, firms:["optiver","imc","js"], title:"Width on the sum of 10 dice",
  prompt:"Make a market on the sum of 10 dice, one contract, then the interviewer says '100 contracts.' Fair value, your quote at each size, and the reasoning.",
  hint:"You computed σ ≈ 5.4 in the variance question. Width scales with size and risk.",
  solution:"Fair = 35, σ ≈ 5.4.\n1 contract: risk is trivial → quote tight to attract flow, e.g. 34 / 36.\n100 contracts: your P&L swing is 100 × (outcome − price); a 1σ move is ±540. Quote wider and skewed to where you'd manage inventory, e.g. 31 / 39, or quote a smaller size.\nStructure of a good answer: (i) fair value from linearity, (ii) width from σ × size and your risk appetite, (iii) explicitly say that width buys you protection against both variance and informed counterparties, (iv) offer to tighten if allowed to hedge or see flow." },
{ id:"mm4", topic:"mm", diff:2, ans:{"t":"n","v":60,"label":"tightest no-loss ASK"}, firms:["js","sig","citadel"], title:"Quoting against an informed trader",
  prompt:"A coin is fair with prob ½ and 60%-heads with prob ½. You must quote a two-sided market on 100 × P(heads). Your counterparty KNOWS the coin. What's the tightest market you can quote without expected loss, and what does this teach about spreads?",
  hint:"Your fair is 55. Their fair is either 50 or 60. Where must your bid and ask sit?",
  solution:"Unconditional fair = ½·50 + ½·60 = 55. The informed counterparty values the coin at exactly 50 or 60.\nIf your ask < 60 they buy only when it's the 60 coin — you lose (60 − ask) whenever they trade. If your bid > 50 they sell you the fair coin — you lose (bid − 50).\nZero-expected-loss market against pure informed flow: 50 bid / 60 ask — the spread must span every value the informed side might know.\nAgainst a MIX of informed and uninformed flow, you can quote inside 50/60: uninformed losses subsidize the spread (Glosten–Milgrom). The spread is not greed — it is exactly the insurance premium for trading with people who know more than you, which is why spreads widen when information risk rises (earnings, data prints) and tighten when flow is mostly noise." },
{ id:"mm5", topic:"mm", diff:2, firms:["optiver","imc","tower"], title:"You're getting lifted repeatedly",
  prompt:"You're quoting 99 / 101, size 10, on an asset you think is worth 100. The same counterparty lifts your offer three times in a row. Talk through exactly what you do and why.",
  hint:"Inventory, information, and the difference between the two.",
  solution:"After fill 1: you're short 10 at 101. Two forces: inventory (you want to buy back → shade quotes UP is wrong for inventory alone... careful: short inventory means you raise your bid to attract sellers... but information says the buyer may know it's worth more) — both point the same direction here: move the market UP.\nRe-quote e.g. 100/102. Fill 2 at 102: move again, 101/103, and consider cutting size. Fill 3: you are now short 30 into persistent informed-looking flow — move fair materially (maybe 103), widen, reduce size, and think about hedging/buying back some short even at a loss.\nThe skill being tested: (1) you always have a position after a fill and must requote off your NEW risk, (2) repeated one-way flow is information, (3) losses should be cut by updating fair, not defended by freezing.\nBonus point: markouts — check what price did AFTER each fill; consistent adverse markouts = you're the exit liquidity." },

/* ---------- Options ---------- */
{ id:"o1", topic:"options", diff:2, ans:{"t":"n","v":2,"label":"riskless profit per package ($)"}, firms:["sig","citadel","imc"], title:"Put-call parity arbitrage",
  prompt:"Same strike/expiry, zero rates: stock = 100, K = 100 call = 5, put = 3. Is there an arbitrage? Construct it and state the profit.",
  hint:"C − P should equal S − K (zero rates).",
  solution:"Parity: C − P = S − K = 0, but market says C − P = 2 → the call is rich vs. the put.\nConversion: sell call (+5), buy put (−3), buy stock (−100). Net outlay 98.\nAt expiry, either the call is assigned or you exercise the put — both deliver the stock at 100. Riskless profit: 100 − 98 = 2 per package (× carry adjustments = 0 here).\nParity is the one identity you must be able to deploy under pressure: C − P = S − PV(K) always, model-free, dividends adjusted via PV." },
{ id:"o2", topic:"options", diff:1, ans:{"t":"n","v":2,"rel":0.05,"label":"implied daily move at 32 vol (%)"}, firms:["sig","optiver","imc"], title:"Rule of 16",
  prompt:"A stock moves about 1% a day. Roughly what annualized volatility is that? A different name has 32 vol into earnings — what daily move is the market implying?",
  hint:"√252 ≈ 16.",
  solution:"Annual vol ≈ daily vol × √252 ≈ 1% × 15.9 ≈ 16%.\n32 vol → 32/16 = 2% implied daily move.\nThe 'rule of 16' converts between the vol quoted on screens and the daily move your intuition understands; every options desk interview touches it. Bonus: for a single earnings day, compare straddle price to the rest-of-month vol to isolate the event move." },
{ id:"o3", topic:"options", diff:2, firms:["sig","citadel","fiverings"], title:"Why is ATM delta about 0.5?",
  prompt:"Explain, without formulas first, why an at-the-money call has delta ≈ 0.5, why deep ITM → 1 and deep OTM → 0. Then connect delta to a probability, including the caveat.",
  hint:"Think of delta as a hedge ratio and as a moneyness probability.",
  solution:"Intuition: ATM, the option gains on the up-half of outcomes and loses nothing extra on the down-half — it responds to about half of the stock's moves. Deep ITM it behaves like stock (delta→1); deep OTM it barely responds (delta→0).\nDelta ≈ N(d₁) ≈ risk-neutral P(finish ITM) (which is N(d₂)) — close but not equal; the gap grows with vol and time (d₁ = d₂ + σ√T). ATM delta is actually slightly ABOVE 0.5 because the lognormal drift term shifts d₁ positive.\nSharp follow-up to expect: 'is delta the probability of finishing ITM?' Correct answer: 'approximately, but it overstates it; N(d₂) is the risk-neutral probability.'" },
{ id:"o4", topic:"options", diff:2, ans:{"t":"n","v":-1,"abs":0.01,"label":"cost of the 90/100/110 butterfly"}, firms:["sig","citadel","optiver"], title:"Butterfly says no-arb",
  prompt:"Calls, same expiry: K=90 → 12, K=100 → 7, K=110 → 1. Find the arbitrage and the rule it violates.",
  hint:"Call prices must be convex in strike.",
  solution:"Butterfly: buy 90C, sell 2× 100C, buy 110C. Cost = 12 − 14 + 1 = −1: you're PAID 1 to own it.\nPayoff of a long butterfly is ≥ 0 everywhere (tent peaking +10 at 100). Negative cost + nonnegative payoff = arbitrage.\nRule violated: convexity of calls in strike — C(100) ≤ ½[C(90) + C(110)] = 6.5, but C(100) = 7.\nThis is precisely the check a vol market maker's fitter runs across the whole strike ladder: butterflies ≥ 0 (convexity), call spreads between 0 and width (monotonicity) — the exact constraints in this app's vol-fitting game." },
{ id:"o5", topic:"options", diff:2, firms:["sig","imc","citadel"], title:"Digital as a call spread",
  prompt:"How would you price and replicate a digital option that pays $1 if the stock ends above 100? What does the replication tell you about its greeks near expiry?",
  hint:"Tighten a call spread around the strike.",
  solution:"Replicate with 1/(2ε) × [C(100−ε) − C(100+ε)] → as ε→0, price = −∂C/∂K ≈ N(d₂) (risk-neutral prob of finishing above 100).\nPractically you PRICE it as a tight call spread you can actually trade, and the skew correction matters: digital = N(d₂) − vega·(dσ/dK) — with typical negative skew this raises the digital's value... (sign depends on convention; the point is the skew term).\nGreeks: near expiry near the strike, delta and gamma blow up (the payoff is a step) — which is why real desks book digitals as call spreads with a width they can hedge, not as true digitals." },

/* ---------- Fermi ---------- */
{ id:"f1", topic:"fermi", diff:1, ans:{"t":"f","v":80,"factor":3,"label":"piano tuners (within x3 counts)"}, firms:["js","sig","optiver"], title:"Piano tuners in Chicago",
  prompt:"Estimate the number of piano tuners in Chicago. Structure the estimate as a market maker would — with an uncertainty band.",
  hint:"Households → pianos → tunings/year ÷ tunings per tuner-year.",
  solution:"Chicago ≈ 2.7M people ≈ 1M households. Pianos: ~1 in 20 households + schools/churches/venues → ~60k pianos.\nTuned ~1×/year → 60k tunings. A tuner does ~4/day × 250 days = 1,000/year.\nEstimate: 60k/1k ≈ 60 tuners; band 40–120.\nReality check: Chicago listings show on the order of 50–100. The classic Fermi grading: each factor within 2× keeps the product within ~3×." },
{ id:"f2", topic:"fermi", diff:1, ans:{"t":"f","v":19000000,"factor":3,"label":"ping pong balls (within x3)"}, firms:["js","hrt","jump"], title:"Ping pong balls in a 747",
  prompt:"How many ping pong balls fit inside a Boeing 747? Give a number and a 90% confidence interval you'd actually make a market on.",
  hint:"Cabin as a cylinder; don't forget packing efficiency.",
  solution:"Cabin ≈ cylinder r ≈ 3 m, length ≈ 60 m → ~1,700 m³; add cargo, subtract seats/structure → usable ~1,000 m³ = 10⁹ cm³.\nBall: d = 4 cm → volume ≈ 33.5 cm³. Random packing ≈ 64%.\n10⁹ × 0.64 / 33.5 ≈ 19M. Quote ~10M–30M.\nGrading notes: remembering packing fraction is the differentiator; and quoting the CI shows you think in distributions, not points." },
{ id:"f3", topic:"fermi", diff:1, ans:{"t":"f","v":370000000,"factor":3,"label":"gallons/day (within x3)"}, firms:["citadel","deshaw","sig"], title:"US gasoline burned per day",
  prompt:"Estimate US gasoline consumption in gallons per day, from the ground up.",
  hint:"Cars × miles per day ÷ mpg.",
  solution:"~230M light vehicles; ~30 miles/day average; ÷ 25 mpg → 230M × 30/25 ≈ 275M gallons/day. Add trucks' gasoline share modestly → ~300M.\nActual: ≈ 370M gallons/day (≈ 8.8M barrels × 42). Within 25% — good.\nSanity anchor worth memorizing: US total oil ≈ 20M barrels/day, roughly half-ish gasoline. Cross-checking two independent paths is what separates a trader's estimate from a guess." },
{ id:"f4", topic:"fermi", diff:1, ans:{"t":"f","v":1200000000,"factor":2.5,"label":"units/year (within x2.5)"}, firms:["js","imc","optiver"], title:"Smartphones sold per year",
  prompt:"Estimate global smartphone unit sales per year.",
  hint:"Installed base ÷ replacement cycle.",
  solution:"~8B people, ~5.5B smartphone users (rough two-thirds+). Replacement cycle ~3.5 years.\nSales ≈ 5.5B/3.5 + first-time buyers ≈ 1.4–1.6B... call it ~1.5B; actual recent years ≈ 1.2B (cycle lengthened).\nStock ÷ flow (installed base over replacement cycle) is the master template — it prices razors, cars, elevators, and most 'units per year' questions." },
{ id:"f5", topic:"fermi", diff:2, ans:{"t":"f","v":12000,"factor":3,"label":"airborne right now (within x3)"}, firms:["js","jump","hrt"], title:"Planes in the air right now",
  prompt:"How many commercial airliners are airborne worldwide at this moment (daytime, mid-week)?",
  hint:"Flights per day × average airborne hours ÷ 24.",
  solution:"~100k commercial flights/day globally; average block time ~2 hours → 200k airborne-hours/day ÷ 24 ≈ 8,300 airborne on average.\nPeak (daytime overlap of US/Europe/Asia) runs ~1.5× average → 10–15k; FlightRadar-type peaks are indeed ≈ 15–20k including cargo/charter.\nLittle's Law in disguise: planes in air = arrival rate × time in system. Name-dropping Little's Law, correctly, lands well." },
];

/* ---------- Firms ---------- */
const FIRMS = [
  { id:"js", name:"Jane Street", style:"Probability · Market Making",
    blurb:"The canonical prob-and-markets interview. Expect layered probability questions where each answer spawns a harder variant, betting games with real (fake) money, and 'make me a market' on anything. They probe how you think about uncertainty and whether you update fast without flailing.",
    process:"Phone (probability + mental math) → 2-3 rounds of probability/games → market making rounds & 'trading day' style finals.",
    weights:{ prob2:1, mart:.9, games:.9, mm:.9, prob1:.8, markov:.7, fermi:.6, mental:.5, brain:.5, gametheory:.5, stats:.4, options:.3 } },
  { id:"sig", name:"SIG (Susquehanna)", style:"Poker · Options · Decision Theory",
    blurb:"Famously teaches poker to new hires. Interviews stress decision-making under uncertainty, expected value vs. actual decisions, options theory (deepest of any firm at entry level), and sports-betting flavored questions. They want you to reason about YOUR edge and bet sizing, not just compute.",
    process:"Online assessment → phone probability → onsite with poker/betting discussions, options theory, and brainteasers.",
    weights:{ options:1, games:.9, gametheory:.9, prob1:.8, prob2:.8, mm:.7, fermi:.6, mart:.5, brain:.5, mental:.5, stats:.4, markov:.4 } },
  { id:"citadel", name:"Citadel / Citadel Securities", style:"Stats · Finance · Rigor",
    blurb:"More formal than the prop shops: solid statistics, regression, stochastic processes, and finance knowledge alongside probability. CitSec leans market microstructure and fast math; the hedge fund leans research depth. Expect precision to be graded strictly.",
    process:"OA (math/coding) → technical phones → onsite: probability, stats/regression, finance, and (CitSec) market making games.",
    weights:{ stats:1, prob1:.8, prob2:.8, options:.8, markov:.7, brain:.7, mm:.6, mental:.5, gametheory:.5, mart:.5, fermi:.4, games:.4 } },
  { id:"hrt", name:"Hudson River Trading", style:"Algorithms · Probability",
    blurb:"Algo-heavy: expect real algorithms & data structures questions at near-Google difficulty PLUS sharp probability. Systems intuition matters. The 'Algo' side of this app's coding section is the core of an HRT loop.",
    process:"OA (coding) → algo phone screens → onsite mixing algorithms, probability, and systems/low-level reasoning.",
    weights:{ prob1:.8, markov:.7, prob2:.7, brain:.7, games:.4, stats:.5, mental:.4, gametheory:.5, mm:.3, mart:.4, options:.2, fermi:.4 } },
  { id:"jump", name:"Jump Trading", style:"Coding · Probability · Speed",
    blurb:"Low-latency culture: strong coding, probability, and quick quantitative reasoning. Less market-making theater than JS/Optiver, more 'solve this cleanly and fast.' Brainteasers and random walks appear often.",
    process:"OA → phone (coding + probability) → onsite: algorithms, probability, brainteasers, some systems.",
    weights:{ prob1:.8, markov:.8, brain:.7, prob2:.7, mental:.5, stats:.4, games:.4, gametheory:.4, mm:.3, mart:.3, options:.2, fermi:.5 } },
  { id:"deshaw", name:"D. E. Shaw", style:"Math Depth · Stats",
    blurb:"The most 'pure math' of the group: harder probability, real statistics, estimators, and proof-flavored questions. They'll let a question run 20 minutes and watch how you build structure. Breadth across math > markets knowledge.",
    process:"Phone (probability/stats) → multiple deep technical rounds; questions escalate until you break.",
    weights:{ stats:1, prob2:.9, mart:.8, markov:.8, brain:.8, prob1:.8, gametheory:.6, mental:.3, options:.3, mm:.3, games:.4, fermi:.4 } },
  { id:"fiverings", name:"Five Rings", style:"Games · Strategy",
    blurb:"Game-playing culture (founded by poker/games people): expect actual games in interviews — auctions, betting games, combinatorial games — plus probability. They watch you find equilibria and exploit non-equilibrium play.",
    process:"Phone probability → rounds built around playing/analyzing games and betting against the interviewer.",
    weights:{ gametheory:1, games:.9, brain:.8, mart:.7, prob1:.7, prob2:.7, mm:.5, markov:.6, mental:.4, options:.4, stats:.3, fermi:.4 } },
  { id:"optiver", name:"Optiver", style:"Mental Math · Options MM",
    blurb:"The 80-questions-in-8-minutes arithmetic test is the front door — raw speed and accuracy matter more here than anywhere. Then options market making: quoting, width, hedging intuition. Dutch-school market making at its purest.",
    process:"80-in-8 math test → sequence/logic tests → phone → onsite market making games and options intuition.",
    weights:{ mental:1, mm:.9, options:.8, games:.6, prob2:.6, prob1:.6, fermi:.5, stats:.4, brain:.4, gametheory:.4, markov:.3, mart:.3 } },
  { id:"imc", name:"IMC Trading", style:"Speed Math · Options",
    blurb:"Similar profile to Optiver: timed arithmetic screens, options market making, quoting games at onsite. Slightly more emphasis on teamwork/trading simulations in final rounds.",
    process:"Timed math OA → cognitive tests → interviews with quoting games and probability.",
    weights:{ mental:1, options:.8, mm:.8, games:.5, prob1:.6, prob2:.6, fermi:.5, stats:.4, brain:.4, gametheory:.3, markov:.3, mart:.3 } },
  { id:"tower", name:"Tower Research", style:"Coding · Quant",
    blurb:"Engineering-forward HFT: strong coding and practical quant questions; probability appears but algorithmic problem solving dominates. The pandas/data side of the coding tab mirrors their data-heavy research screens.",
    process:"OA → coding rounds → quant/probability round → team fit.",
    weights:{ prob1:.6, markov:.5, stats:.6, prob2:.6, brain:.5, mental:.4, games:.3, gametheory:.3, mm:.3, mart:.3, options:.2, fermi:.3 } },
];

/* ---------- Fermi questions for the market game ---------- */
/* scale: divide truth by scale to get the traded price (keeps books readable). */
const FERMI_MARKETS = [
  { q:"How many seconds are there in a calendar year (365 days)?", unit:"millions of seconds", truth:31.536, tick:0.25, decimals:2,
    derivation:"365 × 24 × 3600 = 31,536,000 ≈ 31.54M seconds. (Handy trader constant: 1 year ≈ π × 10⁷ seconds.)" },
  { q:"How many heartbeats does an average human have in a full lifetime?", unit:"billions of beats", truth:2.9, tick:0.05, decimals:2,
    derivation:"~72 bpm × 60 × 24 × 365 ≈ 38M beats/year; × ~77-year lifespan ≈ 2.9B beats. Band: 2.5–3.5B depending on assumed rate and lifespan." },
  { q:"How many golf balls fit inside a standard US school bus?", unit:"thousands of balls", truth:660, tick:5, decimals:0,
    derivation:"Interior ≈ 10m × 2.4m × 1.8m ≈ 43 m³ = 4.3×10⁷ cm³. Golf ball d = 4.3 cm → ~41.6 cm³. Random packing 64%: 4.3e7 × 0.64/41.6 ≈ 660k balls." },
  { q:"How many commercial flights depart worldwide per day?", unit:"thousands of flights", truth:100, tick:1, decimals:0,
    derivation:"~25k airliners in service, ~4 legs/day average utilization ≈ 100k departures/day. Cross-check: ~4.5B passengers/year ÷ ~120 pax/flight ÷ 365 ≈ 100k. Two paths, same answer — that's a tradeable estimate." },
  { q:"What is the total weight of the Eiffel Tower?", unit:"thousands of tonnes", truth:10.1, tick:0.1, decimals:1,
    derivation:"Wrought iron lattice: 7,300 t of iron + lifts, floors, paint ≈ 10,100 t total. Fun check: the iron, melted into its 125m square base, would be only ~6 cm deep — lattice structures are mostly air." },
  { q:"How many slices of pizza are eaten in the US per day?", unit:"millions of slices", truth:30, tick:0.5, decimals:1,
    derivation:"~13% of Americans eat pizza on a given day ≈ 43M people × ~2.8 slices ≈ 120M... industry figure is ~350 slices/second = 30M/day (about 3B pizzas/year ÷ ... 8 slices × 3B/365 ≈ 66M). Estimates span 30–70M; we settle at the widely-cited 350/sec ⇒ 30M. A real market would trade the definition as much as the number — note how much the 'truth' depends on sourcing." },
  { q:"How many piano tuners work in the Chicago metro area?", unit:"tuners", truth:80, tick:1, decimals:0,
    derivation:"9.5M metro population ≈ 3.5M households; ~1 piano per 20 households + institutions ≈ 200k pianos; ~1 tuning/yr ÷ 1,000 tunings per tuner-year ≈ 100–200... professional directories list ~50–100 active. Settle: 80. The gap between model (200) and directory (80) is itself the lesson: utilization assumptions dominate." },
  { q:"How many new cars (light vehicles) are sold worldwide per year?", unit:"millions of cars", truth:75, tick:0.5, decimals:1,
    derivation:"~1.5B vehicles on the road ÷ ~18-year average life ≈ 83M/year replacement + growth − recessions... recent actuals ≈ 75M/year. Stock ÷ lifetime is the workhorse template." },
  { q:"How many kilograms of food does an average American eat per year?", unit:"kg", truth:900, tick:10, decimals:0,
    derivation:"~1.8–2.5 kg/day of food (excluding beverages) → ~700–900 kg/year. USDA availability data ≈ 900 kg. Sanity check via calories: 2,500 kcal/day at ~1.5 kcal/g dense-mix ≈ 1.7 kg/day plus water content in food pushes mass up." },
  { q:"How many words does a typical person speak per day?", unit:"thousands of words", truth:16, tick:0.25, decimals:2,
    derivation:"Recorded-speech studies (Mehl et al. 2007): ~16k words/day for both men and women (the '7k vs 20k' gender factoid is a myth). ~2 hours of actual talking × ~130 wpm ≈ 15.6k ✓." },
];

/* ---------- harder additions ---------- */
QUESTIONS.push(
{ id:"m7", topic:"mental", diff:2, ans:{"t":"n","v":31,"label":"number of digits in 2^100"}, firms:["optiver","hrt","js"], title:"Digits of 2¹⁰⁰",
  prompt:"How many digits does 2¹⁰⁰ have? No calculator. Then: roughly what does the number start with?",
  hint:"Digits of N = ⌊log₁₀N⌋ + 1, and log₁₀2 ≈ 0.30103.",
  solution:"log₁₀(2¹⁰⁰) = 100 × 0.30103 = 30.103 → ⌊30.103⌋ + 1 = 31 digits.\nLeading digits: 10^0.103 ≈ 1.27, so 2¹⁰⁰ ≈ 1.27 × 10³⁰ (exactly 1.2676…×10³⁰).\nThe toolkit: log₁₀2 ≈ 0.301, log₁₀3 ≈ 0.477, log₁₀7 ≈ 0.845, and 2¹⁰ = 1024 ≈ 10³ for quick-and-dirty work. Log fluency is what makes big-number mental math possible at all." },
{ id:"b7", topic:"brain", diff:3, ans:{"t":"n","v":0.31,"abs":0.03,"pct":1,"label":"success probability of the loop strategy"}, firms:["js","deshaw","fiverings"], title:"100 prisoners, 100 boxes",
  prompt:"100 prisoners' names are placed randomly in 100 boxes, one per box. Each prisoner may open 50 boxes looking for their own name; no communication once the searches start. If ALL succeed, everyone goes free. Random guessing gives (1/2)¹⁰⁰ ≈ 0. Find a strategy with ~31% success, and explain why it works.",
  hint:"Number the prisoners and boxes. Follow the permutation: open your own number, then the box of the name you find, and so on.",
  solution:"Loop-following strategy: prisoner k opens box k, reads name j inside, opens box j, and keeps following the chain.\nThe boxes define a random permutation; prisoner k's chain traces the cycle containing k, and they find their own name in ≤ 50 steps iff their cycle has length ≤ 50.\nEveryone succeeds iff the permutation has NO cycle longer than 50. P(some cycle of length ℓ > 50) = Σ_{ℓ=51}^{100} 1/ℓ ≈ ln(100/50) = ln 2 ≈ 0.693 (at most one such cycle can exist).\nSuccess ≈ 1 − ln 2 ≈ 30.7%.\nThe magic: the strategy correlates everyone's failures — either the permutation is bad for many prisoners at once, or good for all. You can't raise each individual's 50% success chance; you CAN make the successes happen together. Correlating your risks on purpose is a deeply trading-flavored idea." },
{ id:"p7", topic:"prob1", diff:3, ans:{"t":"n","v":0.5,"pct":1,"label":"probability for n = 4"}, firms:["js","deshaw","citadel"], title:"All points in a semicircle",
  prompt:"n points are placed independently and uniformly on a circle. What is the probability that all n lie within some semicircle? Compute it for n = 4.",
  hint:"For each point, consider the event that the semicircle starting at that point (going clockwise) contains all the others.",
  solution:"For point i, let A_i = 'the semicircle starting at point i, running clockwise, contains all n points.' The A_i are disjoint (at most one point can be the clockwise-most 'leader'), and each has probability (1/2)^{n−1} (each other point independently falls in that half).\nP = n / 2^{n−1}.\nFor n = 4: 4/8 = 1/2.\nSanity checks: n = 2 gives 1 ✓ (two points always share a semicircle), n = 3 gives 3/4 ✓.\nThe disjointification trick — find an event decomposition indexed by a 'leader' — recurs in many geometric probability questions and is worth internalizing." },
{ id:"e7", topic:"prob2", diff:3, ans:{"t":"n","v":2.71828,"abs":0.03,"label":"expected number of draws"}, firms:["js","sig","deshaw"], title:"Uniforms until the sum exceeds 1",
  prompt:"Draw independent Uniform[0,1] variables one at a time and stop when their sum first exceeds 1. What is the expected number of draws?",
  hint:"Find P(N > n) — it's the volume of a simplex.",
  solution:"P(N > n) = P(U₁ + … + Uₙ ≤ 1) = 1/n! (the volume of the n-dimensional simplex).\nE[N] = Σ_{n≥0} P(N > n) = Σ 1/n! = e ≈ 2.718.\nTwo reusable tools in one question: the tail-sum formula E[N] = ΣP(N > n), and the simplex volume 1/n!.\nFollow-up they sometimes run: expected value of the OVERSHOOT (sum − 1) at stopping ≈ e/2 − 1 + … (harder); or: expected number of draws for the sum to exceed 2 (answer e² − e)." },
{ id:"e8", topic:"prob2", diff:3, ans:{"t":"n","v":3.0,"abs":0.45,"label":"expected max, n = 100"}, firms:["deshaw","citadel","js"], title:"Expected max of 100 normals",
  prompt:"Roughly what is the expected maximum of 100 iid standard normals? Of 10,000? Give the scaling law and why any trader should carry it around.",
  hint:"Set the tail probability ≈ 1/n.",
  solution:"The max sits where the tail holds about 1/n of the mass: P(Z > z) ≈ 1/n → z ≈ √(2 ln n).\nn = 100: √(2 × 4.6) ≈ 3.0. n = 10,000: √(2 × 9.2) ≈ 4.3. (True values ≈ 2.51 and 3.85 — the √(2 ln n) law overshoots slightly but nails the scaling.)\nGrowth is only √log: to add one more sigma to the expected max you must MULTIPLY the number of draws enormously.\nWhy it matters: run 100 random strategies and the best backtest shows ~2.5σ 'significance' by pure luck. The expected-max formula IS the multiple-testing correction — quant research desks (DE Shaw, Citadel) probe exactly this." },
{ id:"g6", topic:"games", diff:3, ans:{"t":"n","v":3,"label":"value of the game ($)"}, firms:["js","sig","fiverings"], title:"Dollar-a-roll die",
  prompt:"You may roll a fair die as many times as you like, paying $1 per roll (including the first). When you stop, you receive the face value of your last roll, in dollars. What's the optimal strategy and the value of the game?",
  hint:"Let V be the value of the game and find the self-consistent stopping set.",
  solution:"Guess the stopping set is {4, 5, 6}: V = −1 + (1/2)(5) + (1/2)V → V = 3.\nConsistency: keep a face iff face ≥ V = 3... face 3 pays exactly V, so you're indifferent; keeping {4,5,6} (or {3,…,6}) both give V = 3. Check {3,4,5,6}: V = −1 + (4/6)(4.5) + (2/6)V → V = 3 ✓ — indeed indifferent.\nValue: $3. Strategy: reroll 1s and 2s (3 is a matter of taste), keep 4+.\nThe general method — value function + self-consistent threshold — is the discrete version of how you price American options. Say that sentence in the interview." },
{ id:"k6", topic:"markov", diff:3, firms:["js","deshaw","fiverings"], title:"Pólya's urn",
  prompt:"An urn starts with 1 red and 1 blue ball. Repeatedly: draw a ball uniformly, put it back along with one more of the same color. (a) What's the probability the 10th draw is red? (b) What does the red fraction converge to?",
  hint:"(a) has a symmetry answer. For (b), show the red fraction is a martingale — then find the limit's distribution.",
  solution:"(a) 1/2 — by symmetry between colors at every step (exchangeability). More strikingly, the probability the n-th draw is red is 1/2 for ALL n.\n(b) The red fraction is a martingale (check: from (r, b), E[next fraction] = current fraction). Bounded martingales converge — but to a RANDOM limit: for the 1+1 start, the limiting red fraction is Uniform[0, 1].\nSo 'rich get richer' dynamics converge, but where they converge is pure luck of the early draws.\nInterview traps: people answer (a) with heavy computation instead of symmetry, and assume (b) converges to 1/2. The urn is the canonical model for path dependence — early random advantages that lock in — from market-share races to order-flow toxicity." },
{ id:"mg6", topic:"mart", diff:3, firms:["js","deshaw"], title:"The monkey types ABRACADABRA",
  prompt:"A monkey types uniform random capital letters forever. What is the expected number of keystrokes until 'ABRACADABRA' first appears? Give the exact closed form.",
  hint:"The martingale-casino argument from HTH generalizes: which prefixes of ABRACADABRA are also suffixes?",
  solution:"Fair-casino argument: before each keystroke a new gambler bets $1 that the next 11 letters spell ABRACADABRA, parlaying at fair 26× odds per letter. At the completion time T, total stakes paid in = E[T], and surviving wealth = Σ 26^k over each prefix of the pattern that is also a suffix.\nABRACADABRA's borders: the whole word (11), 'ABRA' (4), and 'A' (1).\nE[T] = 26¹¹ + 26⁴ + 26 ≈ 3.67 × 10¹⁵.\nThe overlap terms mean self-similar patterns take LONGER to appear than non-overlapping ones — the same reason waiting for HH (6) beats waiting for HT (4). Full credit requires naming the optional stopping theorem and why T is a legal stopping time." },
{ id:"s7", topic:"stats", diff:3, firms:["citadel","deshaw","tower"], title:"Noise in x: attenuation bias",
  prompt:"You want the true regression y = βx + ε, but you only observe x* = x + u (measurement noise, independent). You regress y on x*. What does your slope estimate converge to, and what does this mean for trading signals?",
  hint:"Compute Cov(y, x*)/Var(x*).",
  solution:"β̂ → Cov(y, x*)/Var(x*) = β·σ²ₓ / (σ²ₓ + σ²ᵤ) = β · (signal / (signal + noise)).\nErrors in the regressor bias the slope TOWARD ZERO (attenuation) — never away. Noise in y doesn't bias β; noise in x does.\nTrading translation: your predictive signal is always measured with noise, so the fitted response to it systematically understates the true response — and the noisier the feature, the more shrinkage. This is also why naively 'cleaning' the target but not the features changes nothing, and why Bayesian shrinkage of betas is the right instinct rather than a hack.\nFollow-up to expect: how to fix it (instrumental variables, or SNR-based deattenuation if σ²ᵤ is known)." },
{ id:"s8", topic:"stats", diff:3, ans:{"t":"n","v":0.33333,"rel":0.02,"pct":1,"label":"P(both > 0) at rho = 1/2"}, firms:["deshaw","citadel","js"], title:"P(both positive) for correlated normals",
  prompt:"X, Y are standard normals with correlation ρ. Find P(X > 0 and Y > 0). Verify it makes sense at ρ = 0, 1, −1, and compute it for ρ = 1/2.",
  hint:"Write Y = ρX + √(1−ρ²)Z and think in angles — or quote the orthant formula.",
  solution:"Orthant probability: P(X > 0, Y > 0) = 1/4 + arcsin(ρ)/(2π).\nGeometric proof sketch: (X, Y) = radially symmetric Gaussian in the plane after writing Y = ρX + √(1−ρ²)Z; the event is a wedge of angle (π/2 + arcsin ρ) out of 2π.\nChecks: ρ = 0 → 1/4 ✓ (independence). ρ = 1 → 1/4 + 1/4 = 1/2 ✓ (X = Y). ρ = −1 → 0 ✓.\nρ = 1/2: arcsin(1/2) = π/6 → 1/4 + 1/12 = 1/3.\nDesk relevance: this is exactly 'probability both assets are up' as a function of correlation — and note how NONLINEAR it is: going from ρ = 0.5 to ρ = 1 adds as much probability as 0 to 0.5." },
{ id:"mm6", topic:"mm", diff:3, firms:["js","citadel","optiver"], title:"Two market makers, one market",
  prompt:"You and a rival both quote the same instrument; flow hits whoever posts the better price. Walk through the game theory: where do spreads end up, why don't they go to zero, and what happens if your rival is slower than you?",
  hint:"Start from Bertrand competition, then add the costs that stop the race.",
  solution:"Pure Bertrand logic: undercut by a tick to capture ALL the flow → rival undercuts back → spreads compress until quoting tighter loses money. Equilibrium spread = the marginal COST of providing liquidity, which is not zero:\n• adverse selection (Glosten–Milgrom): each fill has expected loss to informed flow — the spread must cover it;\n• inventory risk: holding positions costs variance × risk aversion;\n• tick size & queue: you can't undercut by less than a tick, so at the constrained tick, PRIORITY (speed) decides who trades — this is why sub-penny economics turn into a latency race.\nIf you're faster: you can quote the same price but always be first in queue, and you can cancel stale quotes before being picked off — speed converts directly into both more volume and less adverse selection. That's the entire HFT business model in one question.\nGreat candidates connect all three: spread floor = adverse selection + inventory cost, competition drives you TO the floor, speed decides allocation AT the floor." },
{ id:"o6", topic:"options", diff:2, ans:{"t":"n","v":11.6,"rel":0.07,"label":"straddle price ($)"}, firms:["sig","optiver","imc"], title:"Straddle rule of thumb",
  prompt:"Derive the trader's approximation for an at-the-money straddle price in terms of S, σ, and T. A stock at $200 with 25 vol and a month to expiry: price the straddle in your head.",
  hint:"ATM call ≈ 0.4·S·σ√T.",
  solution:"ATM (zero rates) call = S[N(d₁) − N(d₂)] with d₁ = −d₂ = σ√T/2 → C ≈ S·φ(0)·σ√T = 0.3989·S·σ√T ≈ 0.4·S·σ√T.\nStraddle = call + put ≈ 0.8·S·σ√T.\nExample: S = 200, σ = 0.25, T = 1/12 → √T ≈ 0.289 → straddle ≈ 0.8 × 200 × 0.25 × 0.289 ≈ $11.6 (call ≈ $5.8).\nEquivalently: straddle ≈ 0.8 × implied move-to-expiry. Interviewers at options shops expect this in seconds; it's also how you sanity-check a screen price before quoting." },
{ id:"f6", topic:"fermi", diff:2, ans:{"t":"f","v":600000000000,"factor":3,"label":"$ notional/day (within x3)"}, firms:["citadel","js","tower"], title:"US equity volume per day",
  prompt:"Estimate the total dollar notional traded in US equities on a normal day. Build it from pieces, then name a cross-check.",
  hint:"Shares per day × average price, or market cap × annual turnover.",
  solution:"Path 1: ~11–12B shares/day trade across US venues; average traded price ~$50–60 → ~$600B/day.\nPath 2: US market cap ~$55–60T; annual turnover very roughly 2–3× ÷ 250 days → $450–700B/day. Paths agree → tradeable estimate: ~$500–700B.\nGarnish for the interviewer: ~40–50% of that is off-exchange (dark/internalized), SPY alone does ~$30–40B, and volume roughly doubles on index-rebalance and OpEx days. Knowing the market's daily notional cold is table stakes for market-structure conversations at CitSec/Tower." }
);
